package com.hms.helper;

import java.sql.SQLException;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.hms.dao.DoctorDao;
import com.hms.exception.UserNotFoundException;
import com.hms.exception.UsernameAlreadyExistsException;
import com.hms.exceptionmapper.HmsBusinessException;
import com.hms.exceptionmapper.HmsSystemException;
import com.hms.model.Doctor;
import com.hms.model.Patient;

/**
 *
 * This Class is used to provide different helper methods to the Delegate layer
 * primarily the DoctorDelegate Class.
 *
 * @author Rahul.
 *
 */
public class DoctorHelper {

	private static final Logger LOGGER = LoggerFactory.getLogger(DoctorHelper.class);

	private DoctorDao doctorDao = new DoctorDao();

	/**
	 *
	 * This method passes the input as a doctor to the DoctorDao and gets the
	 * database created Doctor in return.
	 *
	 * @param doctor object from createDoctor Delegate method.
	 * @return doctor object generated by createDoctor DAO method.
	 * @throws HmsBusinessException           generic client exception.
	 * @throws HmsSystemException             generic system exception.
	 * @throws UsernameAlreadyExistsException custom exception.
	 */
	public Doctor createDoctor(Doctor doctor) throws HmsBusinessException, HmsSystemException {
		LOGGER.trace(
				"Entered the createDoctor Helper method with doctor object with username: " + doctor.getUsername());
		try {
			Doctor createdDoctor = doctorDao.createDoctor(doctor);
			createdDoctor.setPassword(null);
			LOGGER.trace("exited the createDoctor Helper with doctor object with id: " + createdDoctor.getUserId());
			return createdDoctor;
		} catch (UsernameAlreadyExistsException e) {
			LOGGER.warn("User cannot be added: " + e.getMessage());
			throw new HmsBusinessException(e.getMessage());
		} catch (Exception e) {
			LOGGER.debug("System Error Occured.");
			throw new HmsSystemException("System Fail");
		}
	}

	/**
	 * Outputs all the doctors from the DAO method.
	 *
	 * @return list of doctors to the delegate layer.
	 * @throws HmsBusinessException generic Client Exception.
	 * @throws HmsSystemException   generic Business Exception.
	 */
	public List<Doctor> readDoctors() throws HmsBusinessException, HmsSystemException {
		LOGGER.trace("Entered the readDoctors Helper method");
		List<Doctor> doctors = null;
		try {
			doctors = doctorDao.readDoctors();
		} catch (SQLException e) {
			throw new HmsSystemException("SQL error: " + e.getMessage());
		} catch (Exception e) {
			throw new HmsSystemException("System Error: " + e.getMessage());
		}
		if (doctors == null) {
			throw new HmsBusinessException("No users found.");
		}

		LOGGER.trace("Exited the readDoctors Helper method");
		return doctors;
	}

	/**
	 * Outputs all the doctors from the DAO method.
	 *
	 * @param id of the doctor.
	 * @return doctor with userId = id to the delegate layer.
	 * @throws HmsBusinessException client exception.
	 * @throws HmsSystemException   system failure exception.
	 */
	public Doctor readDoctor(int id) throws HmsBusinessException, HmsSystemException {
		LOGGER.trace("Entered the readDoctor Helper method");
		Doctor doctor;
		try {
			doctor = doctorDao.readDoctor(id);
			if (doctor != null) {
				doctor.setPassword(null);
			}
		} catch (UserNotFoundException e) {
			LOGGER.warn("User cannot be read" + e.getMessage());
			throw new HmsBusinessException(e.getMessage());
		} catch (SQLException e) {
			LOGGER.debug("SQL error occurred: " + e.getMessage());
			throw new HmsSystemException("SQL exception occured");
		} catch (Exception e) {
			LOGGER.debug("System Fail: " + e.getMessage());
			throw new HmsSystemException("System failed");
		}

		LOGGER.trace("Exited the readDoctor Helper method");
		return doctor;
	}

	/**
	 * This method is used to delete a given doctor's info in the DAO.
	 *
	 * @param doctor who needs to be deleted.
	 * @return true if doctor deleted else false.
	 * @throws HmsSystemException   generic system exception.
	 * @throws HmsBusinessException generic client exception.
	 */
	public boolean deleteDoctor(Doctor doctor) throws HmsSystemException, HmsBusinessException {
		LOGGER.trace("Entered the deleteDoctor Helper method with id: " + doctor.getUserId());
		boolean status;
		try {
			status = doctorDao.deleteDoctor(doctor.getUserId());
		} catch (SQLException e) {
			LOGGER.debug("Some SQL error occured: " + e.getMessage());
			throw new HmsSystemException("SQL Exception Ocurred: " + e.getMessage());
		} catch (Exception e) {
			LOGGER.debug("System Failed: " + e.getMessage());
			throw new HmsSystemException("System Error");
		}
		if (!status) {
			LOGGER.warn("User is not found to delete.");
			throw new HmsBusinessException("User with Id not found.");
		}
		LOGGER.trace("Exited the deletePatient Helper method");
		return status;
	}

	/**
	 *
	 * @param id of the doctor.
	 * @return List of patients of that doctor.
	 * @throws HmsBusinessException generic Client Exception.
	 * @throws HmsSystemException   generic System Exception.
	 */
	public List<Patient> patientsForDoctor(int id) throws HmsBusinessException, HmsSystemException {
		LOGGER.trace("Enter the patientsForDoctors method with id: " + id);
		List<Patient> patients = null;

		try {
			patients = doctorDao.patientsForDoctor(id);
		} catch (SQLException e) {
			LOGGER.debug("Some SQL error occured: " + e.getMessage());
			throw new HmsSystemException("SQL Error: " + e.getMessage());
		} catch (Exception e) {
			LOGGER.debug("System Failed: " + e.getMessage());
			throw new HmsSystemException("System Error: " + e.getMessage());
		}

		if (patients.size() == 0) {
			LOGGER.warn("No Patients Found");
			throw new HmsBusinessException("No Patients Found.");
		}
		LOGGER.trace("Exit the patientsForDoctors method");
		return patients;

	}

	/**
	 *
	 * @return map of doctors and list of patients.
	 * @throws HmsSystemException   generic System Exception.
	 * @throws HmsBusinessException generic client Exception.
	 */
	public Map<Integer, List<Patient>> patientsForDoctors() throws HmsSystemException, HmsBusinessException {
		LOGGER.trace("Enter the patientsForDoctors method");
		Map<Integer, List<Patient>> map = null;
		try {
			map = doctorDao.patientsForDoctors();
		} catch (SQLException e) {
			LOGGER.debug("Some SQL error occured: " + e.getMessage());
			throw new HmsSystemException("SQL Error: " + e.getMessage());
		} catch (Exception e) {
			LOGGER.debug("System Failed: " + e.getMessage());
			throw new HmsSystemException("System Error: " + e.getMessage());
		}
		if (map == null) {
			throw new HmsBusinessException("No Users Found.");
		}
		LOGGER.trace("Exit the patientsForDoctors method");
		return map;
	}
}
