package com.hms.helper;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.hms.dao.PatientDao;
import com.hms.exception.UsernameAlreadyExistsException;
import com.hms.model.Patient;

/**
 *
 * This Class is used to provide different helper methods to the Delegate layer
 * primarily the PatientDelegate Class.
 *
 * @author Rahul
 *
 */
public class PatientHelper {

	private static final Logger LOGGER = LoggerFactory.getLogger(PatientHelper.class);

	private PatientDao patientDao = new PatientDao();

	/**
	 *
	 * This method passes the input as a patient to the PatientDao and gets the
	 * database created Patient in return.
	 *
	 * @param patient object from createPatient Delegate method.
	 * @return patient object generated by createPatient DAO method.
	 * @throws UsernameAlreadyExistsException custom exception.
	 */
	public Patient createPatient(Patient patient) throws UsernameAlreadyExistsException {
		LOGGER.info(
				"Entered the createPatient Helper method with patient object with username: " + patient.getUsername());
		Patient createdPatient = patientDao.createPatient(patient);
		LOGGER.info("exited the createPatient Helper with patient object with id: " + createdPatient.getUserId());
		return createdPatient;
	}

}
